### ISSUE TITLE
Add Sacrifice bottom button

### ISSUE THREAD

**Issue by kajfik** [antimatter-dimensions/mobile-issues#85]

**Comment by kajfik** [comment]
Won't add - there's no space for it and Sacrifice autobuyer is good enough.

**Comment by OvermindDL1** [comment]
I'm not saying add this, because I don't really see any benefit to it either, but there is still plenty of button space left at the bottom:
![Screenshot_20191029-054532](https://user-images.githubusercontent.com/401605/67764407-7ff92a80-fa0f-11e9-9c37-81fdfaf87c29.png)

It's not even 3/4 of the way.  🙂
(I have the system blue filter enabled so ignore the color shifting.)

**Comment by kajfik** [comment]
@OvermindDL1 
As you can see there's no space for it on my device.
![Screenshot_20191029-125501](https://user-images.githubusercontent.com/20711517/67765020-77bee080-fa4b-11e9-9a93-26aee6a76212.jpg)
